# Generated by Django 5.1.2 on 2024-11-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='val_password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
