# Generated by Django 5.1.2 on 2024-11-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_val_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='image')),
                ('category', models.CharField(choices=[('Chess', 'Chess'), ('CounterStrike', 'CounterStrike'), ('GTA', 'GTA'), ('VALORANT', 'VALORANT'), ('FIFA', 'FIFA')], default='GTA', max_length=200)),
            ],
        ),
    ]
