# Generated by Django 5.1.2 on 2024-11-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
