# Generated by Django 5.1.2 on 2024-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(upload_to='users'),
        ),
    ]
