# Generated by Django 5.1.2 on 2024-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='/image/default.png', upload_to='users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='val_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
