# Generated by Django 5.1.2 on 2024-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_games_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
